name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

#      - name: Build and Test
#        run: |
#          ./gradlew build
#          if [ "${{ matrix.target }}" = "jvm" ]; then
#            ./gradlew jvmTest
#          elif [ "${{ matrix.target }}" = "js" ]; then
#            ./gradlew jsTest
#          elif [ "${{ matrix.target }}" = "macosArm64" ]; then
#            ./gradlew macosArm64Test
#          fi

      - name: build(macOS)
        if: matrix.os == 'macos-latest'
        run: |
          ./gradlew build

      - name: build(Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./gradlew build

