name: Deploy to central

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: build
    strategy:
      matrix:
        include:
          - target: publishMacArm64PublicationToMavenCentralRepository
            os: macos-latest
          - target: publishJvmPublicationToMavenCentralRepository
            os: ubuntu-latest
          - target: publishJsPublicationToMavenCentralRepository
            os: ubuntu-latest
          - target: publishLinuxX64PublicationToMavenCentralRepository
            os: ubuntu-latest
          - target: publishKotlinMultiplatformPublicationToMavenCentralRepository
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Show Version Number
        id: version
        run: |
          echo "Version=${{ github.event.release.tag_name }}"
      - name: Gradle publish
        uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
        with:
          arguments: |
            -PmavenCentralUsername=${{secrets.OSSRH_USERNAME}}
            -PmavenCentralPassword=${{secrets.OSSRH_PASSWORD}}
            -PsigningInMemoryKeyId=${{secrets.OSSRH_GPG_SECRET_KEY_ID}}
            -PsigningInMemoryPassword=${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}
            ${{ matrix.target }}
        env:
          LIB_VERSION: ${{ github.event.release.tag_name }}
